---
#- name: Import In Memory Inventory
#  import_playbook: in_memory_inventory.yml
- name: Good Ansible Role based play
  hosts: all
  become: True
  gather_facts: false   # Speeds up the execution
  roles:

    - role: HAproxy
      when: inventory_hostname in groups['frontends']
      
    - role: apache
      when: inventory_hostname in groups['apps']

    - role: tomcat
      when: inventory_hostname in groups['apps']

    - role: postgresql
      when: inventory_hostname in groups['appdbs']

