---
- name: Good Ansible Role based play
  hosts: all
  gather_facts: false   # Speeds up the execution
  roles:

    - role: HAproxy
      when: inventory_hostname in groups['frontends']
      
    - role: apache
      when: inventory_hostname in groups['apps']

    - role: tomcat
      when: inventory_hostname in groups['apps']

    - role: postgresql
      when: inventory_hostname in groups['appdbs']

